[server]
host = "0.0.0.0"
port = 8443
max_connections = 1000
request_timeout_secs = 30

[ssl]
cert_path = "/etc/letsencrypt/live/tilas.xyz/fullchain.pem"
key_path = "/etc/letsencrypt/live/tilas.xyz/privkey.pem"
cert_check_interval_secs = 3600  # Check every hour

[ttl]
default_ttl_secs = 300      # 5 minutes
max_ttl_secs = 3600         # 1 hour  
cleanup_interval_secs = 60  # Cleanup every minute

[logging]
level = "info"
format = "pretty"  # "pretty" or "json"